export const apiConstant = {
  health: "/health",
  register: "/auth/register",
  logIn: "/auth/login",
  refreshToken: "/auth/refresh-token",
  signOut: "/auth/logout",
  getProfile: "/profile/me",
  updateProfile: "/profile/me",
  uploadResume: "/profile/resume",
  uploadProfilePhoto: "/profile/photo",
  getPublicCompanies: "/companies/public",
  getPublicJobs: "/jobs/public",
  getOpenings: "/jobs/openings",
  getOpeningFilterOptions: "/jobs/openings/filter-options",
  getOpeningDetails: (id) => `/jobs/openings/${id}`,
  applyToOpening: (jobId) => `/jobs/apply/${jobId}`,
  getOpenLinkOpening: (id) => `/jobs/open-link/${id}`,
  applyViaOpenLink: (id) => `/jobs/open-link/${id}/apply`,
  getStudentApplications: "/applications/my",
  getStudentApplicationFilterOptions: "/applications/my/filter-options",
  getApplicationDetails: (id) => `/applications/my/${id}`,
  withdrawApplication: (id) => `/applications/${id}/withdraw`,
  studentDashboard: "/dashboard/student",
  operationsDashboard: "/dashboard",
  operationsDashboardAlias: "/ops/dashboard",
  getCompanies: "/ops/companies",
  getCompanyFilterOptions: "/ops/companies/filter-options",
  getCompanyDetails: (id) => `/ops/companies/${id}`,
  addCompany: "/ops/companies",
  editCompany: (id) => `/ops/companies/${id}`,
  deleteCompany: (id) => `/ops/companies/${id}`,
  toggleCompany: (id) => `/ops/companies/${id}/toggle`,
  exportCompaniesExcel: "/ops/companies/export",
  getStudents: "/ops/students",
  getStudentFilterOptions: "/ops/students/filter-options",
  getStudentDetails: (id) => `/ops/students/${id}`,
  editStudent: (id) => `/ops/students/${id}`,
  disableStudent: (id) => `/ops/students/${id}/disable`,
  deleteStudent: (id) => `/ops/students/${id}`,
  downloadResume: (id) => `/ops/students/${id}/resume`,
  exportStudentsExcel: "/ops/students/export",
  getOperationsOpenings: "/ops/jobs",
  getOperationsOpeningFilterOptions: "/ops/jobs/filter-options",
  createOpening: "/ops/jobs",
  updateOpening: (id) => `/ops/jobs/${id}`,
  deleteOpening: (id) => `/ops/jobs/${id}`,
  closeOpening: (id) => `/ops/jobs/${id}/close`,
  reopenOpening: (id) => `/ops/jobs/${id}/reopen`,
  updateOpeningOpenLink: (id) => `/ops/jobs/${id}/open-link`,
  closeOpeningOpenLink: (id) => `/ops/jobs/${id}/open-link/close`,
  duplicateOpening: (id) => `/ops/jobs/${id}/duplicate`,
  exportJobsExcel: "/ops/jobs/export",
  getJobApplicants: (id) => `/ops/jobs/${id}/applicants`,
  getApplicants: "/ops/applications",
  getApplicantFilterOptions: "/ops/applications/filter-options",
  getApplicantDetails: (id) => `/ops/applications/${id}`,
  changeApplicantStatus: (id) => `/ops/applications/${id}/status`,
  downloadApplicantResume: (id) => `/ops/applications/${id}/resume`,
  exportApplicantsExcel: "/ops/applications/export",
  getMyIssues: "/issues/my",
  getRaisedIssues: "/issues/raised",
  createIssue: "/issues",
  updateIssueStatus: (id) => `/issues/${id}/status`
};
